# #MailMate API V1
#
##MailMate physical mail management API.  ## Authentication  All protected endpoints use [DeviseTokenAuth](https://devise-token-auth.gitbook.io/devise-token-auth/). Call `POST /api/v1/auth/sign_in` and read the three response **headers**: `access-token`, `client`, and `uid`. Include all three on every subsequent request. Tokens rotate on each request — always persist the latest values returned. 
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.21.0
#

require "../spec_helper"

# Unit tests for MailMateAPI::AuthApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe "AuthApi" do
  describe "test an instance of AuthApi" do
    it "should create an instance of AuthApi" do
      api_instance = MailMateAPI::AuthApi.new
      expect(api_instance).to be_instance_of(MailMateAPI::AuthApi)
    end
  end

  # unit tests for api_v1_auth_sign_in_post
  # Sign in — obtain auth tokens
  # Authenticates a user and returns auth tokens as **response headers**: &#x60;access-token&#x60;, &#x60;client&#x60;, &#x60;uid&#x60;, &#x60;expiry&#x60;, &#x60;token-type&#x60;. Store all five and include them on every subsequent request. 
  # @param [Hash] opts the optional parameters
  # @option opts [ApiV1AuthSignInPostRequest] :api_v1_auth_sign_in_post_request 
  # @return [ApiV1AuthSignInPost200Response]
  describe "api_v1_auth_sign_in_post test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_auth_sign_out_delete
  # Sign out — invalidate tokens
  # @param access_token 
  # @param client 
  # @param uid 
  # @param [Hash] opts the optional parameters
  # @return [ApiV1AuthSignOutDelete200Response]
  describe "api_v1_auth_sign_out_delete test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
