# #MailMate API V1
#
##MailMate physical mail management API.  ## Authentication  All protected endpoints use [DeviseTokenAuth](https://devise-token-auth.gitbook.io/devise-token-auth/). Call `POST /api/v1/auth/sign_in` and read the three response **headers**: `access-token`, `client`, and `uid`. Include all three on every subsequent request. Tokens rotate on each request — always persist the latest values returned. 
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.21.0
#

require "../spec_helper"

# Unit tests for MailMateAPI::InboxesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe "InboxesApi" do
  describe "test an instance of InboxesApi" do
    it "should create an instance of InboxesApi" do
      api_instance = MailMateAPI::InboxesApi.new
      expect(api_instance).to be_instance_of(MailMateAPI::InboxesApi)
    end
  end

  # unit tests for api_v1_inboxes_get
  # List inboxes
  # @param access_token 
  # @param client 
  # @param uid 
  # @param [Hash] opts the optional parameters
  # @option opts [Int32] :page Page number (default 1)
  # @option opts [Int32] :per_page Items per page (default 20)
  # @return [JsonapiCollection]
  describe "api_v1_inboxes_get test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_inboxes_id_get
  # Get inbox by ID
  # @param id 
  # @param access_token 
  # @param client 
  # @param uid 
  # @param [Hash] opts the optional parameters
  # @return [ApiV1InboxesIdGet200Response]
  describe "api_v1_inboxes_id_get test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_inboxes_list_get
  # Flat list of all inboxes (used for inbox picker)
  # @param access_token 
  # @param client 
  # @param uid 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "api_v1_inboxes_list_get test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
