# #MailMate API V1
#
##MailMate physical mail management API.  ## Authentication  All protected endpoints use [DeviseTokenAuth](https://devise-token-auth.gitbook.io/devise-token-auth/). Call `POST /api/v1/auth/sign_in` and read the three response **headers**: `access-token`, `client`, and `uid`. Include all three on every subsequent request. Tokens rotate on each request — always persist the latest values returned. 
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.21.0
#

require "../spec_helper"

# Unit tests for MailMateAPI::ItemsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe "ItemsApi" do
  describe "test an instance of ItemsApi" do
    it "should create an instance of ItemsApi" do
      api_instance = MailMateAPI::ItemsApi.new
      expect(api_instance).to be_instance_of(MailMateAPI::ItemsApi)
    end
  end

  # unit tests for api_v1_inboxes_inbox_id_postal_mails_get
  # List mail items
  # @param inbox_id 
  # @param access_token 
  # @param client 
  # @param uid 
  # @param [Hash] opts the optional parameters
  # @option opts [Int32] :page 
  # @option opts [Int32] :per_page 
  # @option opts [String] :keyword Full-text search
  # @option opts [Time] :received_after ISO 8601 date e.g. 2024-01-01
  # @option opts [Time] :received_up_until 
  # @option opts [Time] :updated_after 
  # @option opts [Time] :updated_up_until 
  # @return [JsonapiCollection]
  describe "api_v1_inboxes_inbox_id_postal_mails_get test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_inboxes_inbox_id_postal_mails_id_get
  # Get mail item detail
  # Returns full mail item metadata. Scanned file contents (images, PDFs) are embedded as pre-signed S3 URLs in the &#x60;mail_items&#x60; relationship data — these are the links used by &#x60;mailmate items:info &lt;id&gt; --json&#x60;. 
  # @param inbox_id 
  # @param id 
  # @param access_token 
  # @param client 
  # @param uid 
  # @param [Hash] opts the optional parameters
  # @return [ApiV1InboxesIdGet200Response]
  describe "api_v1_inboxes_inbox_id_postal_mails_id_get test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for api_v1_inboxes_inbox_id_postal_mails_id_open_mail_patch
  # Request mail to be opened/scanned
  # Queues the physical mail item to be opened and scanned. Processing takes up to 24 hours.
  # @param inbox_id 
  # @param id 
  # @param access_token 
  # @param client 
  # @param uid 
  # @param [Hash] opts the optional parameters
  # @return [ApiV1InboxesInboxIdPostalMailsIdOpenMailPatch200Response]
  describe "api_v1_inboxes_inbox_id_postal_mails_id_open_mail_patch test" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
