# #MailMate API V1
#
##MailMate physical mail management API.  ## Authentication  All protected endpoints use [DeviseTokenAuth](https://devise-token-auth.gitbook.io/devise-token-auth/). Call `POST /api/v1/auth/sign_in` and read the three response **headers**: `access-token`, `client`, and `uid`. Include all three on every subsequent request. Tokens rotate on each request — always persist the latest values returned. 
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.21.0
#

module MailMateAPI
  class JsonapiResource
    include JSON::Serializable
    include YAML::Serializable

    # Required properties
    @[JSON::Field(key: "id", type: String, nillable: false, emit_null: false)]
    property id : String

    @[JSON::Field(key: "type", type: String, nillable: false, emit_null: false)]
    property _type : String

    @[JSON::Field(key: "attributes", type: JSON::Any, nillable: false, emit_null: false)]
    property attributes : JSON::Any

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@id : String, @_type : String, @attributes : JSON::Any)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(other)
      return true if self.same?(other)
      self.class == other.class &&
          id == other.id &&
          _type == other._type &&
          attributes == other.attributes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(other)
      self == other
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, _type, attributes].hash
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_h.to_s
    end

    # to_body is an alias to to_h (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_h
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_h
      hash = NetboxClient::RecursiveHash.new
      hash["id"] = _to_h(id)
      hash["type"] = _to_h(_type)
      hash["attributes"] = _to_h(attributes)
      hash.to_h
    end

    # Outputs non-array value in the form of hash
    # For object, use to_h. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    private def _to_h(value)
      return nil if value.nil?

      if value.is_a?(Hash)
        hash = NetboxClient::RecursiveHash.new
        value.each { |k, v| hash[k] = _to_h(v) }
        hash
      elsif value.is_a?(Array)
        value.compact.map { |v| _to_h(v) }
      elsif value.responds_to?(:to_h)
        value.to_h
      else
        value
      end
    end

  end

end
