# #MailMate API V1
#
##MailMate physical mail management API.  ## Authentication  All protected endpoints use [DeviseTokenAuth](https://devise-token-auth.gitbook.io/devise-token-auth/). Call `POST /api/v1/auth/sign_in` and read the three response **headers**: `access-token`, `client`, and `uid`. Include all three on every subsequent request. Tokens rotate on each request — always persist the latest values returned. 
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.21.0
#

require "../spec_helper"

# Unit tests for MailMateAPI::ApiV1AuthSignInPostRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe MailMateAPI::ApiV1AuthSignInPostRequest do

  describe "test an instance of ApiV1AuthSignInPostRequest" do
    skip "should create an instance of ApiV1AuthSignInPostRequest" do
      #instance = MailMateAPI::ApiV1AuthSignInPostRequest.new
      #expect(instance).to be_instance_of(MailMateAPI::ApiV1AuthSignInPostRequest)
    end
  end
  describe "test attribute 'email'" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'password'" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
