# #MailMate API V1
#
##MailMate physical mail management API.  ## Authentication  All protected endpoints use [DeviseTokenAuth](https://devise-token-auth.gitbook.io/devise-token-auth/). Call `POST /api/v1/auth/sign_in` and read the three response **headers**: `access-token`, `client`, and `uid`. Include all three on every subsequent request. Tokens rotate on each request — always persist the latest values returned. 
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.21.0
#

require "uri"

module MailMateAPI
  class AuthApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Sign in — obtain auth tokens
    # Authenticates a user and returns auth tokens as **response headers**: `access-token`, `client`, `uid`, `expiry`, `token-type`. Store all five and include them on every subsequent request. 
    # @return [SignIn200Response]
    def sign_in(sign_in_request : SignInRequest? = nil)
      data, _status_code, _headers = sign_in_with_http_info(sign_in_request)
      data
    end

    # Sign in — obtain auth tokens
    # Authenticates a user and returns auth tokens as **response headers**: &#x60;access-token&#x60;, &#x60;client&#x60;, &#x60;uid&#x60;, &#x60;expiry&#x60;, &#x60;token-type&#x60;. Store all five and include them on every subsequent request. 
    # @return [Array<(SignIn200Response, Integer, Hash)>] SignIn200Response data, response status code and response headers
    def sign_in_with_http_info(sign_in_request : SignInRequest? = nil)
      if @api_client.config.debugging
        Log.debug {"Calling API: AuthApi.sign_in ..."}
      end
      # resource path
      local_var_path = "/api/v1/auth/sign_in"

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String | Array(String)).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      # HTTP header "Content-Type"
      header_params["Content-Type"] = @api_client.select_header_content_type(["application/json"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = sign_in_request.to_json

      # auth_names
      auth_names = [] of String

      data, status_code, headers = @api_client.call_api(
        http_method: :POST,
        path: local_var_path,
        operation: :"AuthApi.sign_in",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        query_params: query_params,
        cookie_params: cookie_params,
        form_params: form_params
      )

      if @api_client.config.debugging
        Log.debug {"API called: AuthApi#sign_in\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end

      return SignIn200Response.from_json(data), status_code, headers
    end

    # Sign out — invalidate tokens
    # @param access_token [String] 
    # @param client [String] 
    # @param uid [String] 
    # @return [SignOut200Response]
    def sign_out(access_token : String, client : String, uid : String)
      data, _status_code, _headers = sign_out_with_http_info(access_token, client, uid)
      data
    end

    # Sign out — invalidate tokens
    # @param access_token [String] 
    # @param client [String] 
    # @param uid [String] 
    # @return [Array<(SignOut200Response, Integer, Hash)>] SignOut200Response data, response status code and response headers
    def sign_out_with_http_info(access_token : String, client : String, uid : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: AuthApi.sign_out ..."}
      end
      # verify the required parameter "access_token" is set
      if @api_client.config.client_side_validation && access_token.nil?
        raise ArgumentError.new("Missing the required parameter 'access_token' when calling AuthApi.sign_out")
      end
      # verify the required parameter "client" is set
      if @api_client.config.client_side_validation && client.nil?
        raise ArgumentError.new("Missing the required parameter 'client' when calling AuthApi.sign_out")
      end
      # verify the required parameter "uid" is set
      if @api_client.config.client_side_validation && uid.nil?
        raise ArgumentError.new("Missing the required parameter 'uid' when calling AuthApi.sign_out")
      end
      # resource path
      local_var_path = "/api/v1/auth/sign_out"

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String | Array(String)).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      header_params["access-token"] = access_token
      header_params["client"] = client
      header_params["uid"] = uid

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # auth_names
      auth_names = ["access_token", "uid", "client_id"]

      data, status_code, headers = @api_client.call_api(
        http_method: :DELETE,
        path: local_var_path,
        operation: :"AuthApi.sign_out",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        query_params: query_params,
        cookie_params: cookie_params,
        form_params: form_params
      )

      if @api_client.config.debugging
        Log.debug {"API called: AuthApi#sign_out\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end

      return SignOut200Response.from_json(data), status_code, headers
    end
  end
end
