# #MailMate API V1
#
##MailMate physical mail management API.  ## Authentication  All protected endpoints use [DeviseTokenAuth](https://devise-token-auth.gitbook.io/devise-token-auth/). Call `POST /api/v1/auth/sign_in` and read the three response **headers**: `access-token`, `client`, and `uid`. Include all three on every subsequent request. Tokens rotate on each request — always persist the latest values returned. 
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.21.0
#

require "uri"

module MailMateAPI
  class InboxesApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get inbox by ID
    # @param id [Int32] 
    # @param access_token [String] 
    # @param client [String] 
    # @param uid [String] 
    # @return [GetInbox200Response]
    def get_inbox(id : Int32, access_token : String, client : String, uid : String)
      data, _status_code, _headers = get_inbox_with_http_info(id, access_token, client, uid)
      data
    end

    # Get inbox by ID
    # @param id [Int32] 
    # @param access_token [String] 
    # @param client [String] 
    # @param uid [String] 
    # @return [Array<(GetInbox200Response, Integer, Hash)>] GetInbox200Response data, response status code and response headers
    def get_inbox_with_http_info(id : Int32, access_token : String, client : String, uid : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: InboxesApi.get_inbox ..."}
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling InboxesApi.get_inbox")
      end
      # verify the required parameter "access_token" is set
      if @api_client.config.client_side_validation && access_token.nil?
        raise ArgumentError.new("Missing the required parameter 'access_token' when calling InboxesApi.get_inbox")
      end
      # verify the required parameter "client" is set
      if @api_client.config.client_side_validation && client.nil?
        raise ArgumentError.new("Missing the required parameter 'client' when calling InboxesApi.get_inbox")
      end
      # verify the required parameter "uid" is set
      if @api_client.config.client_side_validation && uid.nil?
        raise ArgumentError.new("Missing the required parameter 'uid' when calling InboxesApi.get_inbox")
      end
      # resource path
      local_var_path = "/api/v1/inboxes/{id}".sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String | Array(String)).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      header_params["access-token"] = access_token
      header_params["client"] = client
      header_params["uid"] = uid

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # auth_names
      auth_names = ["access_token", "uid", "client_id"]

      data, status_code, headers = @api_client.call_api(
        http_method: :GET,
        path: local_var_path,
        operation: :"InboxesApi.get_inbox",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        query_params: query_params,
        cookie_params: cookie_params,
        form_params: form_params
      )

      if @api_client.config.debugging
        Log.debug {"API called: InboxesApi#get_inbox\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end

      return GetInbox200Response.from_json(data), status_code, headers
    end

    # List inboxes
    # @param access_token [String] 
    # @param client [String] 
    # @param uid [String] 
    # @return [JsonapiCollection]
    def list_inboxes(access_token : String, client : String, uid : String, page : Int32? = nil, per_page : Int32? = nil)
      data, _status_code, _headers = list_inboxes_with_http_info(access_token, client, uid, page, per_page)
      data
    end

    # List inboxes
    # @param access_token [String] 
    # @param client [String] 
    # @param uid [String] 
    # @return [Array<(JsonapiCollection, Integer, Hash)>] JsonapiCollection data, response status code and response headers
    def list_inboxes_with_http_info(access_token : String, client : String, uid : String, page : Int32? = nil, per_page : Int32? = nil)
      if @api_client.config.debugging
        Log.debug {"Calling API: InboxesApi.list_inboxes ..."}
      end
      # verify the required parameter "access_token" is set
      if @api_client.config.client_side_validation && access_token.nil?
        raise ArgumentError.new("Missing the required parameter 'access_token' when calling InboxesApi.list_inboxes")
      end
      # verify the required parameter "client" is set
      if @api_client.config.client_side_validation && client.nil?
        raise ArgumentError.new("Missing the required parameter 'client' when calling InboxesApi.list_inboxes")
      end
      # verify the required parameter "uid" is set
      if @api_client.config.client_side_validation && uid.nil?
        raise ArgumentError.new("Missing the required parameter 'uid' when calling InboxesApi.list_inboxes")
      end
      # resource path
      local_var_path = "/api/v1/inboxes"

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String | Array(String)).new
      query_params["page"] = page.to_s unless page.nil?
      query_params["per_page"] = per_page.to_s unless per_page.nil?

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      header_params["access-token"] = access_token
      header_params["client"] = client
      header_params["uid"] = uid

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # auth_names
      auth_names = ["access_token", "uid", "client_id"]

      data, status_code, headers = @api_client.call_api(
        http_method: :GET,
        path: local_var_path,
        operation: :"InboxesApi.list_inboxes",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        query_params: query_params,
        cookie_params: cookie_params,
        form_params: form_params
      )

      if @api_client.config.debugging
        Log.debug {"API called: InboxesApi#list_inboxes\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end

      return JsonapiCollection.from_json(data), status_code, headers
    end

    # Flat list of all inboxes (used for inbox picker)
    # @param access_token [String] 
    # @param client [String] 
    # @param uid [String] 
    # @return [nil]
    def list_inboxes_flat(access_token : String, client : String, uid : String)
      list_inboxes_flat_with_http_info(access_token, client, uid)
      nil
    end

    # Flat list of all inboxes (used for inbox picker)
    # @param access_token [String] 
    # @param client [String] 
    # @param uid [String] 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def list_inboxes_flat_with_http_info(access_token : String, client : String, uid : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: InboxesApi.list_inboxes_flat ..."}
      end
      # verify the required parameter "access_token" is set
      if @api_client.config.client_side_validation && access_token.nil?
        raise ArgumentError.new("Missing the required parameter 'access_token' when calling InboxesApi.list_inboxes_flat")
      end
      # verify the required parameter "client" is set
      if @api_client.config.client_side_validation && client.nil?
        raise ArgumentError.new("Missing the required parameter 'client' when calling InboxesApi.list_inboxes_flat")
      end
      # verify the required parameter "uid" is set
      if @api_client.config.client_side_validation && uid.nil?
        raise ArgumentError.new("Missing the required parameter 'uid' when calling InboxesApi.list_inboxes_flat")
      end
      # resource path
      local_var_path = "/api/v1/inboxes_list"

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String | Array(String)).new

      # header parameters
      header_params = Hash(String, String).new
      header_params["access-token"] = access_token
      header_params["client"] = client
      header_params["uid"] = uid

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # auth_names
      auth_names = ["access_token", "uid", "client_id"]

      data, status_code, headers = @api_client.call_api(
        http_method: :GET,
        path: local_var_path,
        operation: :"InboxesApi.list_inboxes_flat",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        query_params: query_params,
        cookie_params: cookie_params,
        form_params: form_params
      )

      if @api_client.config.debugging
        Log.debug {"API called: InboxesApi#list_inboxes_flat\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end

      return nil, status_code, headers
    end
  end
end
