# #MailMate API V1
#
##MailMate physical mail management API.  ## Authentication  All protected endpoints use [DeviseTokenAuth](https://devise-token-auth.gitbook.io/devise-token-auth/). Call `POST /api/v1/auth/sign_in` and read the three response **headers**: `access-token`, `client`, and `uid`. Include all three on every subsequent request. Tokens rotate on each request — always persist the latest values returned. 
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.21.0
#

require "uri"

module MailMateAPI
  class ItemsApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get mail item detail
    # Returns full mail item metadata. Scanned file contents (images, PDFs) are embedded as pre-signed S3 URLs in the `mail_items` relationship data — these are the links used by `mailmate items:info <id> --json`. 
    # @param inbox_id [Int32] 
    # @param id [Int32] 
    # @param access_token [String] 
    # @param client [String] 
    # @param uid [String] 
    # @return [GetInbox200Response]
    def get_item(inbox_id : Int32, id : Int32, access_token : String, client : String, uid : String)
      data, _status_code, _headers = get_item_with_http_info(inbox_id, id, access_token, client, uid)
      data
    end

    # Get mail item detail
    # Returns full mail item metadata. Scanned file contents (images, PDFs) are embedded as pre-signed S3 URLs in the &#x60;mail_items&#x60; relationship data — these are the links used by &#x60;mailmate items:info &lt;id&gt; --json&#x60;. 
    # @param inbox_id [Int32] 
    # @param id [Int32] 
    # @param access_token [String] 
    # @param client [String] 
    # @param uid [String] 
    # @return [Array<(GetInbox200Response, Integer, Hash)>] GetInbox200Response data, response status code and response headers
    def get_item_with_http_info(inbox_id : Int32, id : Int32, access_token : String, client : String, uid : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: ItemsApi.get_item ..."}
      end
      # verify the required parameter "inbox_id" is set
      if @api_client.config.client_side_validation && inbox_id.nil?
        raise ArgumentError.new("Missing the required parameter 'inbox_id' when calling ItemsApi.get_item")
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling ItemsApi.get_item")
      end
      # verify the required parameter "access_token" is set
      if @api_client.config.client_side_validation && access_token.nil?
        raise ArgumentError.new("Missing the required parameter 'access_token' when calling ItemsApi.get_item")
      end
      # verify the required parameter "client" is set
      if @api_client.config.client_side_validation && client.nil?
        raise ArgumentError.new("Missing the required parameter 'client' when calling ItemsApi.get_item")
      end
      # verify the required parameter "uid" is set
      if @api_client.config.client_side_validation && uid.nil?
        raise ArgumentError.new("Missing the required parameter 'uid' when calling ItemsApi.get_item")
      end
      # resource path
      local_var_path = "/api/v1/inboxes/{inbox_id}/postal_mails/{id}".sub("{" + "inbox_id" + "}", URI.encode_path(inbox_id.to_s)).sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String | Array(String)).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      header_params["access-token"] = access_token
      header_params["client"] = client
      header_params["uid"] = uid

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # auth_names
      auth_names = ["access_token", "uid", "client_id"]

      data, status_code, headers = @api_client.call_api(
        http_method: :GET,
        path: local_var_path,
        operation: :"ItemsApi.get_item",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        query_params: query_params,
        cookie_params: cookie_params,
        form_params: form_params
      )

      if @api_client.config.debugging
        Log.debug {"API called: ItemsApi#get_item\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end

      return GetInbox200Response.from_json(data), status_code, headers
    end

    # List mail items
    # @param inbox_id [Int32] 
    # @param access_token [String] 
    # @param client [String] 
    # @param uid [String] 
    # @return [JsonapiCollection]
    def list_items(inbox_id : Int32, access_token : String, client : String, uid : String, page : Int32? = nil, per_page : Int32? = nil, keyword : String? = nil, received_after : Time? = nil, received_up_until : Time? = nil, updated_after : Time? = nil, updated_up_until : Time? = nil)
      data, _status_code, _headers = list_items_with_http_info(inbox_id, access_token, client, uid, page, per_page, keyword, received_after, received_up_until, updated_after, updated_up_until)
      data
    end

    # List mail items
    # @param inbox_id [Int32] 
    # @param access_token [String] 
    # @param client [String] 
    # @param uid [String] 
    # @return [Array<(JsonapiCollection, Integer, Hash)>] JsonapiCollection data, response status code and response headers
    def list_items_with_http_info(inbox_id : Int32, access_token : String, client : String, uid : String, page : Int32? = nil, per_page : Int32? = nil, keyword : String? = nil, received_after : Time? = nil, received_up_until : Time? = nil, updated_after : Time? = nil, updated_up_until : Time? = nil)
      if @api_client.config.debugging
        Log.debug {"Calling API: ItemsApi.list_items ..."}
      end
      # verify the required parameter "inbox_id" is set
      if @api_client.config.client_side_validation && inbox_id.nil?
        raise ArgumentError.new("Missing the required parameter 'inbox_id' when calling ItemsApi.list_items")
      end
      # verify the required parameter "access_token" is set
      if @api_client.config.client_side_validation && access_token.nil?
        raise ArgumentError.new("Missing the required parameter 'access_token' when calling ItemsApi.list_items")
      end
      # verify the required parameter "client" is set
      if @api_client.config.client_side_validation && client.nil?
        raise ArgumentError.new("Missing the required parameter 'client' when calling ItemsApi.list_items")
      end
      # verify the required parameter "uid" is set
      if @api_client.config.client_side_validation && uid.nil?
        raise ArgumentError.new("Missing the required parameter 'uid' when calling ItemsApi.list_items")
      end
      # resource path
      local_var_path = "/api/v1/inboxes/{inbox_id}/postal_mails".sub("{" + "inbox_id" + "}", URI.encode_path(inbox_id.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String | Array(String)).new
      query_params["page"] = page.to_s unless page.nil?
      query_params["per_page"] = per_page.to_s unless per_page.nil?
      query_params["keyword"] = keyword.to_s unless keyword.nil?
      query_params["received_after"] = received_after.to_s unless received_after.nil?
      query_params["received_up_until"] = received_up_until.to_s unless received_up_until.nil?
      query_params["updated_after"] = updated_after.to_s unless updated_after.nil?
      query_params["updated_up_until"] = updated_up_until.to_s unless updated_up_until.nil?

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      header_params["access-token"] = access_token
      header_params["client"] = client
      header_params["uid"] = uid

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # auth_names
      auth_names = ["access_token", "uid", "client_id"]

      data, status_code, headers = @api_client.call_api(
        http_method: :GET,
        path: local_var_path,
        operation: :"ItemsApi.list_items",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        query_params: query_params,
        cookie_params: cookie_params,
        form_params: form_params
      )

      if @api_client.config.debugging
        Log.debug {"API called: ItemsApi#list_items\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end

      return JsonapiCollection.from_json(data), status_code, headers
    end

    # Request mail to be opened/scanned
    # Queues the physical mail item to be opened and scanned. Processing takes up to 24 hours.
    # @param inbox_id [Int32] 
    # @param id [Int32] 
    # @param access_token [String] 
    # @param client [String] 
    # @param uid [String] 
    # @return [OpenItem200Response]
    def open_item(inbox_id : Int32, id : Int32, access_token : String, client : String, uid : String)
      data, _status_code, _headers = open_item_with_http_info(inbox_id, id, access_token, client, uid)
      data
    end

    # Request mail to be opened/scanned
    # Queues the physical mail item to be opened and scanned. Processing takes up to 24 hours.
    # @param inbox_id [Int32] 
    # @param id [Int32] 
    # @param access_token [String] 
    # @param client [String] 
    # @param uid [String] 
    # @return [Array<(OpenItem200Response, Integer, Hash)>] OpenItem200Response data, response status code and response headers
    def open_item_with_http_info(inbox_id : Int32, id : Int32, access_token : String, client : String, uid : String)
      if @api_client.config.debugging
        Log.debug {"Calling API: ItemsApi.open_item ..."}
      end
      # verify the required parameter "inbox_id" is set
      if @api_client.config.client_side_validation && inbox_id.nil?
        raise ArgumentError.new("Missing the required parameter 'inbox_id' when calling ItemsApi.open_item")
      end
      # verify the required parameter "id" is set
      if @api_client.config.client_side_validation && id.nil?
        raise ArgumentError.new("Missing the required parameter 'id' when calling ItemsApi.open_item")
      end
      # verify the required parameter "access_token" is set
      if @api_client.config.client_side_validation && access_token.nil?
        raise ArgumentError.new("Missing the required parameter 'access_token' when calling ItemsApi.open_item")
      end
      # verify the required parameter "client" is set
      if @api_client.config.client_side_validation && client.nil?
        raise ArgumentError.new("Missing the required parameter 'client' when calling ItemsApi.open_item")
      end
      # verify the required parameter "uid" is set
      if @api_client.config.client_side_validation && uid.nil?
        raise ArgumentError.new("Missing the required parameter 'uid' when calling ItemsApi.open_item")
      end
      # resource path
      local_var_path = "/api/v1/inboxes/{inbox_id}/postal_mails/{id}/open_mail".sub("{" + "inbox_id" + "}", URI.encode_path(inbox_id.to_s)).sub("{" + "id" + "}", URI.encode_path(id.to_s))

      # cookie parameters
      cookie_params = Hash(String, String).new

      # query parameters
      query_params = Hash(String, String | Array(String)).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"])
      header_params["access-token"] = access_token
      header_params["client"] = client
      header_params["uid"] = uid

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # auth_names
      auth_names = ["access_token", "uid", "client_id"]

      data, status_code, headers = @api_client.call_api(
        http_method: :PATCH,
        path: local_var_path,
        operation: :"ItemsApi.open_item",
        post_body: post_body,
        auth_names: auth_names,
        header_params: header_params,
        query_params: query_params,
        cookie_params: cookie_params,
        form_params: form_params
      )

      if @api_client.config.debugging
        Log.debug {"API called: ItemsApi#open_item\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end

      return OpenItem200Response.from_json(data), status_code, headers
    end
  end
end
