# #MailMate API V1
#
##MailMate physical mail management API.  ## Authentication  All protected endpoints use [DeviseTokenAuth](https://devise-token-auth.gitbook.io/devise-token-auth/). Call `POST /api/v1/auth/sign_in` and read the three response **headers**: `access-token`, `client`, and `uid`. Include all three on every subsequent request. Tokens rotate on each request — always persist the latest values returned. 
#
#The version of the OpenAPI document: v1
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.21.0
#

# Stdlib dependencies
require "big"
require "json"
require "log"
require "time"
require "yaml"

# External dependencies
require "any_hash"
require "crest"

module MailMateAPI
  Log = ::Log.for("MailMateAPI") # => Log for MailMateAPI source

  VERSION = {{ `shards version #{__DIR__}`.chomp.stringify }}

  # Return the default `Configuration` object.
  def self.configure
    Configuration.default
  end

  # Customize default settings for the SDK using block.
  #
  # ```
  # MailMateAPI.configure do |config|
  #   config.username = "xxx"
  #   config.password = "xxx"
  # end
  # ```
  def self.configure
    yield Configuration.default
  end
end

require "./openapi_client/**"
